version: "3.9"

services:
    server:
        container_name: server
        build: ./server
        ports:
            - "5000:5000"
        networks:
            - transcendence
        restart: unless-stopped
        depends_on:
            - postgres

    client:
        container_name: client
        build: ./client
        ports:
            - "3000:3000"
        networks:
            - transcendence
        restart: unless-stopped

    postgres:
        container_name: postgres
        image: postgres
        restart: unless-stopped
        networks:
            - transcendence

networks:
    transcendence:
